name: Build image and deploy to ECS
on: 
    push:
        branches:
            - main
    workflow_dispatch:     

env:
    NODE_IMAGE_NAME: ecs-demo-node
    REACT_IMAGE_NAME: ecs-demo-client
    AWS_REGION: ap-south-1
    ECS_CLUSTER: ECSdemocluster
    ECS_SERVICE: ECSdemoservice
    ECS_TASK_DEFINITION: ECSdemotd
    NODE_CONTAINER_NAME: nodeappcontrainer
    REACT_CONTAINER_NAME: reactappcontainer

jobs:
    build-image-node:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ vars.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Added details to image
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ vars.DOCKER_USERNAME }}/${{env.NODE_IMAGE_NAME}}
              tags: |
                 latest
                 v1.0.${{github.run_number}}
          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
                context: ./API-jokes
                file: ./API-jokes/Dockerfile.prod
                push: true
                tags: ${{ steps.meta.outputs.tags }}
    
    build-image-react:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ vars.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Added details to image
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ vars.DOCKER_USERNAME }}/${{env.REACT_IMAGE_NAME}}
              tags: |
                 latest
                 v1.0.${{github.run_number}}
          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
                context: ./react-client
                file: ./react-client/Dockerfile.prod
                push: true
                build-args: |
                   VITE_API_BASE_URL=http://ECSLoadbalancer-1667050042.ap-south-1.elb.amazonaws.com
                tags: ${{ steps.meta.outputs.tags }}
    deploy-to-ecs:
        runs-on: ubuntu-latest
        needs: 
            - build-image-node
            - build-image-react
        steps:
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{env.AWS_REGION}} 
          - name: Add Image deatils of node app
            id: task-def
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
                task-definition-famiy: ${{env.ECS_TASK_DEFINITION}}
                container-name: ${{env.NODE_CONTAINER_NAME}}
                image: ${{ vars.DOCKER_USERNAME }}/${{env.NODE_IMAGE_NAME}}  
          - name: Modify Amazon ECS task definition with second container for react
            id: taskdef-react
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
               task-definition: ${{ steps.task-def.outputs.task-definition }}
               container-name: ${{env.REACT_CONTAINER_NAME}}
               image: ${{ vars.DOCKER_USERNAME }}/${{env.REACT_IMAGE_NAME}}  
          - name: Deploy to Amazon ECS service
            uses: aws-actions/amazon-ecs-deploy-task-definition@v2
            with:
                task-definition: ${{ steps.taskdef-react.outputs.task-definition }}
                service: ${{env.ECS_SERVICE}}
                cluster: ${{env.ECS_CLUSTER}}

